apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    io.kompose.service: leader-node
  name: leader-node
spec:
  serviceName: leader-node
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: leader-node
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        io.kompose.service: leader-node
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: false
        fsUser: 0
        #fsGroup: 65534
      initContainers:
      - name: configure
        command: ["bash", "/configmap/initContainer-entrypoint"]
        image: rcmorano/cardano-node:guild-ops-ptn0-leader
        imagePullPolicy: "IfNotPresent"
        env:
        - name: CNODE_PORT
          value: "6000"
        - name: CNODE_HOST_ADDR
          value: "0.0.0.0"
        - name: CNODE_USE_CONFIGMAP
          value: "true"
        - name: CNODE_LOCAL_TOPOLOGY_DISCOVER
          value: "true"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: /opt/cardano/cnode/files.pvc
          name: leader-node-files
        - mountPath: /opt/cardano/cnode/db
          name: leader-node-db
        - mountPath: /configmap
          name: leader-node-configmap
      containers:
      - command: ["bash", "-c", "ls -hal /opt/cardano/cnode/priv/pool/default; export HOME=/nonexistent; source $HOME/.baids/baids && ${NETWORK}-cnode-run-as-${CNODE_ROLE} +RTS -N --disable-delayed-os-memory-return -I0.3 -Iw600 -A32m -F1.5 -H3G -T"]
        env:
        - name: CNODE_PORT
          value: "6000"
        image: rcmorano/cardano-node:guild-ops-ptn0-leader
        imagePullPolicy: "IfNotPresent"
        name: leader-node
        ports:
        - containerPort: 6000
        - containerPort: 12798
        resources:
          #limits:
          #  memory: 700Mi
          requests:
            memory: 2000Mi
            cpu: 500m
        volumeMounts:
        - mountPath: /opt/cardano/cnode/files
          name: leader-node-files
        - mountPath: /opt/cardano/cnode/db
          name: leader-node-db
        - mountPath: /configmap
          name: leader-node-configmap
        - mountPath: /opt/cardano/cnode/priv/pool/default/op.cert
          name: pool-keys
          subPath: op.cert
        - mountPath: /opt/cardano/cnode/priv/pool/default/hot.skey
          name: pool-keys
          subPath: hot.skey
        - mountPath: /opt/cardano/cnode/priv/pool/default/vrf.skey
          name: pool-keys
          subPath: vrf.skey
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: leader-node-configmap
        configMap:
          name: leader-node
      - name: pool-keys
        secret:
          secretName: pool-keys
          defaultMode: 0400
          items:
          - key: hot.skey
            path: hot.skey
            mode: 0400
          - key: vrf.skey
            path: vrf.skey
            mode: 0400
          - key: op.cert
            path: op.cert
            mode: 0400
  volumeClaimTemplates:
  - metadata:
      name: leader-node-files
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
#  - metadata:
#      name: leader-node-priv
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 100Mi
  - metadata:
      name: leader-node-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

