---
apiVersion: v1
kind: Service
metadata:
  name: passive-node
  labels:
    io.kompose.service: passive-node
spec:
  externalTrafficPolicy: Local
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - name: p2p
    port: 6000
    nodePort: 31000
    targetPort: 6000
    protocol: TCP
  selector:
    io.kompose.service: passive-node

---
apiVersion: v1
kind: Service
metadata:
  name: passive-node-headless
  labels:
    io.kompose.service: passive-node
spec:
  sessionAffinity: ClientIP
  clusterIP: None
  type: ClusterIP
  ports:
  - name: p2p
    port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    io.kompose.service: passive-node

---
apiVersion: v1
kind: Service
metadata:
  name: passive-node-metrics
  labels:
    app.kubernetes.io/name: passive-node-metrics
spec:
  sessionAffinity: None
  type: ClusterIP
  ports:
  - name: metrics
    port: 12798
    targetPort: 12798
    protocol: TCP
  selector:
    io.kompose.service: passive-node
